// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_aKwrVEPtsEolY8Cupe8m1Os1aRgnHdA',
    appId: '1:380111969288:web:ca489b92291a898a6645bd',
    messagingSenderId: '380111969288',
    projectId: 'mirai-japanese-n5',
    authDomain: 'mirai-japanese-n5.firebaseapp.com',
    storageBucket: 'mirai-japanese-n5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhzalUZfOYLG7ocjKYsA8j716RxNIHXW4',
    appId: '1:380111969288:android:72aa466172537d866645bd',
    messagingSenderId: '380111969288',
    projectId: 'mirai-japanese-n5',
    storageBucket: 'mirai-japanese-n5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXHk1rejpBD1b2rQFSNuB--KiWUoH3R8w',
    appId: '1:380111969288:ios:252867a3fed0d0296645bd',
    messagingSenderId: '380111969288',
    projectId: 'mirai-japanese-n5',
    storageBucket: 'mirai-japanese-n5.appspot.com',
    iosBundleId: 'com.miraijapanesenflutter.miraijapaneselms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXHk1rejpBD1b2rQFSNuB--KiWUoH3R8w',
    appId: '1:380111969288:ios:252867a3fed0d0296645bd',
    messagingSenderId: '380111969288',
    projectId: 'mirai-japanese-n5',
    storageBucket: 'mirai-japanese-n5.appspot.com',
    iosBundleId: 'com.miraijapanesenflutter.miraijapaneselms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_aKwrVEPtsEolY8Cupe8m1Os1aRgnHdA',
    appId: '1:380111969288:web:afb2c040594721316645bd',
    messagingSenderId: '380111969288',
    projectId: 'mirai-japanese-n5',
    authDomain: 'mirai-japanese-n5.firebaseapp.com',
    storageBucket: 'mirai-japanese-n5.appspot.com',
  );
}
